version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8100:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
