version: '3'

services:
  mongodb:
    image: mongo
    container_name: 7_week_mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "./data/db:/data/db"
    ports:
      - 27017:27017
    networks:
      - default

networks:
  default:
    driver: bridge